version: '3.8'

services:

  nginx:
    image: test_service/nginx-server
    build: ./nginx/
    container_name: nginx-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/cache/:/etc/nginx/cache
      - static_volume:/app/static
    ports:
      - "80:80"
    networks:
      - service_network
    depends_on:
      - app
    restart: always

  app:
    image: test_service/app-service
    build: .
    container_name: app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - service_network
    env_file:
      - .env

networks:
  service_network:

volumes:
  static_volume: