"""Added image table

Revision ID: 1ad67e377dbd
Revises: 
Create Date: 2022-07-19 23:45:56.802146

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1ad67e377dbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('needed_amount_of_shows', sa.Integer(), nullable=True),
    sa.Column('category1', sa.String(), nullable=True),
    sa.Column('category2', sa.String(), nullable=True),
    sa.Column('category3', sa.String(), nullable=True),
    sa.Column('category4', sa.String(), nullable=True),
    sa.Column('category5', sa.String(), nullable=True),
    sa.Column('category6', sa.String(), nullable=True),
    sa.Column('category7', sa.String(), nullable=True),
    sa.Column('category8', sa.String(), nullable=True),
    sa.Column('category9', sa.String(), nullable=True),
    sa.Column('category10', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
